openapi: 3.0.0
info:
  title: Psychiatrist Details API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/psychiatrists:
    post:
      summary: Returns the details of all the psychiatrists, their count along with IDs and patient details for the specified hospital.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                hospitalId:
                  type: number
                  description: Hospital Id.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  hospitalName:
                    type: string
                  psychiatristCount:
                    type: integer
                  TotalpatientCount:
                    type: integer
                  psychiatristDetails:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        patientCount:
                          type: integer
        '404':
          description: Hospital with the specified ID is not found in the database
        '500':
          description: An error occurred while processing the request
  /api/patients:
    post:
      summary: Registers a new patient with the specified details.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 255
                  description: Full name of the patient.
                address:
                  type: string
                  minLength: 10
                  maxLength: 255
                  description: Address of the patient.
                email:
                  type: string
                  format: email
                  description: Email address of the patient.
                phone:
                  type: string
                  pattern: '^\+?[0-9]{10,}$'
                  description: Phone number of the patient, including the country code.
                password:
                  type: string
                  minLength: 8
                  maxLength: 15
                  pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9]+$'
                  description: Password for the patient account. Must contain at least one lowercase, one uppercase character, and one number.
                photo:
                  type: string
                  format: binary
                  description: Photo of the patient.
      responses:
        '200':
          description: Patient registered successfully
        '400':
          description: Invalid request
        '500':
          description: An error occurred while processing the request
